name: "What's the Big Idea? "
favicon: null
layout_spectrum: 0.8271989787463099
typography_spectrum: 0.4173218479845673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7841907462570816
  lightness: 0.4317856135312468
  saturation: 0.09720883192494512
  rhythmicContrast: 0.22834166116081178
purpose: []
